name: Init Project
on: create

jobs:

  init:
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.0
    
    - name: Run go mod init
      run: go mod init github.com/${{github.repository}}
    
    - name: Git Commit/Push Changes
      uses: actions-x/commit@v1
